ignore_files:
  - README.md
  - pkg/rule/default.go

rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
    alternatives:
      - allowlist
    # severity: warn # disabled to show that error is the default

  - name: blacklist
    terms:
      - blacklist
      - black-list
    alternatives:
      - denylist
      - blocklist
    severity: warning
