rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
    alternatives:
      - allowlist
    # severity: warn # disabled to show that error is the default

  - name: blacklist
    terms:
      - blacklist
      - black-list
    alternatives:
      - denylist
      - blocklist
      
  - name: master
    terms:
      - master
    alternatives:
      - leader
      - active
      - primary

  - name: slave
    terms:
      - slave
    alternatives:
      - follower
      - secondary
      - standby
      
  - name: grandfathered
    terms:
      - grandfathered
    alternatives:
      - legacy status
      
  - name: man hours
    terms:
      - man hours
    alternatives:
      - person hours
      - engineer hours
      
  - name: sanity check
    terms:
      - sanity check 
    alternatives:
      - quick check
      - confidence check
      
  - name: dummy value 
    terms:
      - dummy value
    alternatives:
      - sample value
      
  - name: man-in-the-middle
    terms:
      - man-in-the-middle
    alternatives:
      - in-path attack
      
   - name: whitespace
    terms:
      - whitespace
    alternatives:
      - empty-space
      
  - name: mob progamming
    terms:
      - mob programming
    alternatives:
      - herd programming
    severity: warning
